# Generated by Django 4.2.4 on 2023-08-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order_shippingaddress_review_orderitem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='order_item',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
        migrations.AlterModelTable(
            name='shippingaddress',
            table='shipping_address',
        ),
    ]
